---
title: "05_extract_numbers"
author: "Anton Hung"
date: "2025-12-05"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(pillar.sigfig = 4)
```


```{r}
.libPaths(c("~/libs", .libPaths()))
library(lmtp)
library(glue)
library(purrr)
library(dplyr)
library(ggplot2)
library(data.table)
library(knitr)


source("~/medicaid/low-back-therapies/R/helpers.R")

data <- load_data("pain_cohort_clean_imputed.fst", file.path(drv_root_30_day_treatment, "modified_final")) |> as.data.table()

version <- "30_day_exposure"

A <- (c("exposure_acetaminophen",
        # "exposure_acupuncture",
        "exposure_anti_inflammatory",
        "exposure_benzodiazepine",
        "exposure_chiropractic",
        "exposure_other_treatment",
        "exposure_gabapentin",
        "exposure_intervention",
        "exposure_muscle_relaxant",
        "exposure_massage_therapy",
        "exposure_physical_therapy",
        "exposure_steroid",
        # "exposure_opioid",
        # "exposure_max_daily_dose_mme",
        # "exposure_days_supply"
            "exposure_opioid_<=7days_<=50mme",
            "exposure_opioid_>7days_<=50mme",
            "exposure_opioid_>50mme"
))

read_res <- function(Y, intervention) {
  map_dfr(A, function(treatment) {
    file.path(drv_root, "analysis", version,
              glue("fit_{intervention}_outcome_{Y}_treatment_{treatment}.rds")) |> 
      readRDS() |> 
      tidy() |> 
      mutate(treatment = treatment, .before = "estimate")
  })
}

read_relr <- function(Y, intervention1, intervention2) {
  map_dfr(A, function(treatment) {
    diff <- file.path(drv_root, "analysis", version,
                      glue("fit_{intervention1}_outcome_{Y}_treatment_{treatment}.rds")) |> 
      readRDS() |> 
      lmtp_contrast(ref = readRDS(file.path(drv_root, "analysis", version, glue("fit_{intervention2}_outcome_{Y}_treatment_{treatment}.rds"))), 
                    type = "rr")
    mutate(diff$estimates, treatment = treatment, .before = "shift") |> 
      mutate(estimate = estimate - 1,
             conf.low = conf.low - 1,
             conf.high = conf.high - 1)
  })
}

read_relr_no_cens <- function(Y, intervention1) {
  map_dfr(A, function(treatment) {
    diff <- file.path(drv_root, "analysis", version,
                      glue("fit_{intervention1}_outcome_{Y}_treatment_{treatment}.rds")) |> 
      readRDS() |> 
      lmtp_contrast(ref = readRDS(file.path(drv_root, "analysis", version, glue("fit_outcome_{Y}_no_cens.rds"))), 
                    type = "rr")
    mutate(diff$estimates, treatment = treatment, .before = "shift") |> 
      mutate(estimate = estimate - 1,
             conf.low = conf.low - 1,
             conf.high = conf.high - 1)
  })
}

read_diff <- function(Y, intervention1, intervention2) {
  map_dfr(A, function(treatment) {
    diff <- file.path(drv_root, "analysis", version,
                      glue("fit_{intervention1}_outcome_{Y}_treatment_{treatment}.rds")) |> 
      readRDS() |> 
      lmtp_contrast(ref = readRDS(file.path(drv_root, "analysis", version, glue("fit_{intervention2}_outcome_{Y}_treatment_{treatment}.rds"))))
    mutate(diff$estimates, treatment = treatment, .before = "shift") #|>
      # mutate(estimate = shift - ref)
  })
}

read_diff_no_cens <- function(Y, intervention1, intervention2) {
  map_dfr(A, function(treatment) {
    diff <- file.path(drv_root, "analysis", version,
                      glue("fit_{intervention1}_outcome_{Y}_treatment_{treatment}.rds")) |> 
      readRDS() |> 
      lmtp_contrast(ref = readRDS(file.path(drv_root, "analysis", version, glue("fit_outcome_{Y}_no_cens.rds"))))
    mutate(diff$estimates, treatment = treatment, .before = "shift") #|>
    # mutate(estimate = shift - ref)
  })
}
```

```{r}
Y <- "oud_period_1"
print("6 months, on vs off relative risk")

df_1_onvsoff_relrisk <- read_relr(Y, "on", "off")
df_1_onvsoff_relrisk[, c("treatment", "estimate", "conf.low", "conf.high")] |>
  mutate(estimate = round(estimate * 100, 1),
         conf.low = round(conf.low * 100, 1),
         conf.high = round(conf.high * 100, 1))

```

```{r}
Y <- "oud_period_2"

print("12 months, on vs off relative risk")

df_2_onvsoff_relrisk <- read_relr(Y, "on", "off")
df_2_onvsoff_relrisk[, c("treatment", "estimate", "conf.low", "conf.high")] |>
  mutate(estimate = round(estimate * 100, 1),
         conf.low = round(conf.low * 100, 1),
         conf.high = round(conf.high * 100, 1))

```




```{r}
Y <- "oud_period_1"

print("6 months, on vs observed relative risk")

df_1_onvsobserved_relrisk <- read_relr_no_cens(Y, "on")
df_1_onvsobserved_relrisk[, c("treatment", "estimate", "conf.low", "conf.high")] |>
  mutate(estimate = round(estimate * 100, 1),
         conf.low = round(conf.low * 100, 1),
         conf.high = round(conf.high * 100, 1))

```

```{r}
Y <- "oud_period_2"

print("12 months, on vs observed relative risk")

df_2_onvsobserved_relrisk <- read_relr_no_cens(Y, "on")
df_2_onvsobserved_relrisk[, c("treatment", "estimate", "conf.low", "conf.high")] |>
  mutate(estimate = round(estimate * 100, 1),
         conf.low = round(conf.low * 100, 1),
         conf.high = round(conf.high * 100, 1))

```



```{r}
Y <- "oud_period_1"
print("6 months, on vs off absolute risk")

df_1_onvsoff_riskdiff <- read_diff(Y, "on", "off")
df_1_onvsoff_riskdiff[, c("treatment", "estimate", "conf.low", "conf.high")] |>
  mutate(estimate = round(estimate * 100, 1),
         conf.low = round(conf.low * 100, 1),
         conf.high = round(conf.high * 100, 1))

```

```{r}
Y <- "oud_period_2"

print("12 months, on vs off absolute risk")

df_2_onvsoff_riskdiff <- read_diff(Y, "on", "off")
df_2_onvsoff_riskdiff[, c("treatment", "estimate", "conf.low", "conf.high")] |>
  mutate(estimate = round(estimate * 100, 1),
         conf.low = round(conf.low * 100, 1),
         conf.high = round(conf.high * 100, 1))
```



```{r}

print("Make latex table")

result <- cbind(
  df_1_onvsoff_relrisk[, 1],
  sprintf("%.3f (%.3f, %.3f)",
          df_1_onvsoff_riskdiff$estimate,
          df_1_onvsoff_riskdiff$conf.low,
          df_1_onvsoff_riskdiff$conf.high),
  sprintf("%.2f (%.2f, %.2f)",
          df_1_onvsoff_relrisk$estimate + 1,
          df_1_onvsoff_relrisk$conf.low + 1,
          df_1_onvsoff_relrisk$conf.high + 1),
  sprintf("%.3f (%.3f, %.3f)",
          df_2_onvsoff_riskdiff$estimate,
          df_2_onvsoff_riskdiff$conf.low,
          df_2_onvsoff_riskdiff$conf.high),
  sprintf("%.2f (%.2f, %.2f)",
          df_2_onvsoff_relrisk$estimate + 1,
          df_2_onvsoff_relrisk$conf.low + 1,
          df_2_onvsoff_relrisk$conf.high + 1)
)

cat(knitr::kable(
  result,
  format = "latex",
  booktabs = TRUE,
  col.names = c(
    "Treatment",
    "6-month RD (95\\% CI)",
    "6-month RR (95\\% CI)",
    "12-month RD (95\\% CI)",
    "12-month RR (95\\% CI)"
  )
))

```

